# Main configuration file for Mimir-AIP, you can define pipelines to run here (and schedule them in future versions)
pipelines:
  - name: "Test All Functions Pipeline"
    file: "pipelines/TestAllFunctions.yaml"
    enabled: true
    schedule: null  # Remove schedule to run only once
    
  # Example of another pipeline
  # - name: "Twitter Analysis Pipeline"
  #   file: "pipelines/twitter_analysis.yaml"
  #   enabled: false
  #   schedule: "0 */6 * * *"  # Run every 6 hours

settings:
  pipeline_directory: "src/pipelines"
  output_directory: "output"
  log_level: "INFO"
  test_mode: true
