pipelines:
  - name: "Basic Pipeline Demo"
    enabled: true
    steps:
      - name: "Load CSV Input"
        plugin: "Input.csv"
        config:
          file: "data/input.csv"
          columns:
            - name: column1
              type: int
            - name: column2
              type: str
      - name: "Process with Sample Plugin"
        plugin: "Data_Processing.sample_processor"
        config:
          param1: "value1"
          param2: "value2"
      - name: "Export JSON Output"
        plugin: "Output.json_writer"
        config:
          file: "data/output.json"
          fields:
            - name: field1
              type: float
            - name: field2
              type: bool