pipeline:
  name: My Pipeline
  inputs:
    - type: csv
      file: data/input.csv
      columns:
        - name: column1
          type: int
        - name: column2
          type: str
    - type: json
      file: data/input.json
      fields:
        - name: field1
          type: float
        - name: field2
          type: bool
  processing:
    - plugin: data_processing_plugin1
      config:
        param1: value1
        param2: value2
    - plugin: data_processing_plugin2
      config:
        param3: value3
        param4: value4
  outputs:
    - type: csv
      file: data/output.csv
      columns:
        - name: column3
          type: int
        - name: column4
          type: str
    - type: json
      file: data/output.json
      fields:
        - name: field3
          type: float
        - name: field4
          type: bool