# List of pipeline definitions
pipelines:
  - name: "Simple Web Server"
    description: "A simple web server with test endpoints and context management"
    version: "1.0"
    enabled: true
    execution_mode: single

    steps:
      - name: "Start Web Server"
        plugin: "Web.SimpleWebServer"
        config:
          port: 8080
          host: "0.0.0.0"  # Listen on all interfaces
          static_dir: "public"  # Files will be served at /static/*
        
      - name: "Add Test Route"
        plugin: "Web.SimpleWebServer"
        config:
          method: "GET"
          path: "/api/test"
          handler: |
            response = 200, {
                "status": "success",
                "message": "Test endpoint working"
            }

      - name: "Add Counter Route"
        plugin: "Web.SimpleWebServer"
        config:
          method: "GET"
          path: "/api/counter"
          handler: |
            # Initialize counter if it doesn't exist
            if 'counter' not in context:
                context['counter'] = 0
            
            # Increment counter
            context['counter'] += 1
            
            response = 200, {
                "status": "success",
                "counter": context['counter']
            }

      - name: "Initialize Context Data"
        plugin: "Data_Processing.ContextManager"
        config:
          operation: set
          key: "server_info"
          value:
            name: "Test Server"
            version: "1.0.0"
            started_at: ${time.time()}

      - name: "Add Test Data"
        plugin: "Data_Processing.ContextManager"
        config:
          operation: set
          key: "test_data"
          value:
            numbers: [1, 2, 3, 4, 5]
            message: "Hello from context"
            metadata:
              author: "Pipeline"
              purpose: "Testing"

      - name: "Keep Server Running"
        plugin: "Data_Processing.Delay"
        config:
          seconds: 600  # Keep running for 10 minutes
        output: server_running

