pipelines:
  - name: "BBC News Report Generator"
    description: "Generates reports for important news stories from BBC News RSS feed"
    steps:
      - name: "Fetch BBC News RSS Feed"
        plugin: "RSS-Feed"
        config:
          url: "http://feeds.bbci.co.uk/news/world/rss.xml"
          feed_name: "BBC-News"
        output: "feed_data"

      - name: "Determine Importance"
        plugin: "LLMFunction"
        config:
          plugin: "OpenRouter"
          model: "meta-llama/llama-3-8b-instruct:free"
          function: "You are a program block that takes RSS feed items and determines importance on a scale of 1-10"
          format: "return score in the format {'score': 10}"
        input: "feed_data"
        output: "importance_scores"

      - name: "Filter Important Stories"
        condition: "importance_scores.score > 7"
        output: "important_stories"

      - name: "Generate Search Queries"
        plugin: "LLMFunction"
        config:
          plugin: "OpenRouter"
          model: "meta-llama/llama-3-8b-instruct:free"
          function: "You are a program block that generates search queries for a given topic"
          format: "return search queries in the format {'search_queries': ['query1', 'query2', 'query3']}"
        input: "important_stories"
        output: "search_queries"

      - name: "Fetch Search Results"
        plugin: "WebSearch"
        config:
          query: "search_queries"
        output: "search_results"

      - name: "Generate Report"
        plugin: "LLMFunction"
        config:
          plugin: "OpenRouter"
          model: "meta-llama/llama-3-8b-instruct:free"
          function: "You are a program block that generates a report from search results"
          format: "return report in the format {'report': 'report text'}"
        input: "search_results"
        output: "report"

      - name: "Output Report"
        action: "print"#just printing to terminal for now, will add html report generation in the future
        input: "report"