name: Build & Package Binaries

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ['3.10']
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build with PyInstaller (one-dir + include data)
        shell: bash
        run: |
          SEPARATOR=":"
          if [[ "$RUNNER_OS" == "Windows" ]]; then SEPARATOR=";"; fi
          pyinstaller \
            --clean \
            --onedir \
            --name mimir-aip-${{ matrix.os }} \
            --add-data "config.yaml${SEPARATOR}." \
            --add-data "src/pipelines${SEPARATOR}pipelines" \
            --add-data "src/Plugins${SEPARATOR}Plugins" \
            src/main.py

      - name: Zip platform bundle (non-Windows)
        if: runner.os != 'Windows'
        run: |
          cd dist
          zip -r ../mimir-aip-${{ matrix.os }}.zip mimir-aip-${{ matrix.os }} src/pipelines config.yaml src/Plugins
          cd ..

      - name: Zip platform bundle (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Compress-Archive -Path "dist\mimir-aip-${{ matrix.os }}" -DestinationPath "mimir-aip-${{ matrix.os }}.zip"

      - name: Create GitHub Release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: mimir-aip-${{ matrix.os }}.zip
          asset_name: mimir-aip-${{ matrix.os }}.zip
          asset_content_type: application/zip
